name: Reposaur
author: Reposaur Authors
description: Audit your GitHub data using custom policies written in Rego

branding:
  icon: lock
  color: purple

runs:
  using: composite
  steps:
    - run: |
        curl -o- https://raw.githubusercontent.com/reposaur/reposaur/v0.3.0/install.sh | bash
        echo "${{ github.action_path }}" >> $GITHUB_PATH
      working-directory: ${{ github.action_path }}
      shell: bash
